### ISSUE TITLE
Not compiling on Android

### ISSUE THREAD

**Issue by sy1vain** [jlorente/cordova-plugin-volume-control#1]
The problem is a missing `;` [here](https://github.com/jlorente/cordova-plugin-volume-control/blob/6a8ee19cf519590de56355482615340d3d64b46f/src/android/VolumeControl.java#L42) (line 42 in VolumeControl.java)

**Comment by christoph-schindler** [comment]
trying it with PhoneGap Build, i see the same error in logs ...iOS build fails, too

**Comment by sy1vain** [comment]
In iOS it fails because of the DLog statements that don't get included apparently, I did a quick fix for that as well on my own fork ( sy1vain/cordova-plugin-volume-control ) , will do a pull request here.

**Comment by jlorente** [comment]
Thanks for the contribution sy1vain. Currently I have few time to dedicate to the project, but I will try to launch a release version soon.
