### ISSUE TITLE
Build fails in Cordova

### ISSUE THREAD

**Issue by blukis** [jlorente/cordova-plugin-volume-control#3]
Including this plugin with this in my config.xml:
```<plugin name="cordova-plugin-volume-control" version="0.1.8" />```

Getting this error when building with cordova:
```
Error: cmd: Command failed with exit code 1 Error output:
C:\Projects\gogyup-literacy-app\litapp-source\builds\build-cordova-litapp2\platforms\android\src\com\lorentech\plugins\vo
lumeControl\VolumeControl.java:42: error: ';' expected
                                int volumeToSet = (int) Math.round(args.getDouble(0) * 100.0f)
                                                                                              ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I suspect the latest github version is not uploaded to npm, as the semi-colon looks ok in latest github source.  But the VolumeControl.java in my local plugins/cordova-plugin-volume-control/src/android folder is missing the semi-colon, like the error message indicates.

**Comment by jlorente** [comment]
You are right. I have published it now. Thanks for the warning.
